// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xoqlejueizrdclvlkylj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvcWxlanVlaXpyZGNsdmxreWxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMTA2NTMsImV4cCI6MjA1ODU4NjY1M30.wHAEyluNoCUZVcH2xBNLhHPOL2l2S-GRk0i8B-mMYHs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);